project_id = "xqvjjfbzgjhutvhfrrbu"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.chat]
    verify_jwt = false
  [functions.contact]
    verify_jwt = false
  [functions.notify-service-request]
    verify_jwt = false
